@Net9LayeredApi.API_HostAddress = http://localhost:5002

### Health Check
GET {{Net9LayeredApi.API_HostAddress}}/ping

### Get All Users
GET {{Net9LayeredApi.API_HostAddress}}/api/users
Accept: application/json

###
